version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  myapp:
    image: najmasyarifa/tugas1_bigdata:v3
    container_name: myapp
    ports:
      - "80:80"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
